# Generated by Django 5.1.2 on 2024-10-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=6, unique=True),
        ),
    ]
